/**
 * Real-date guard for content generation.
 *
 * Root cause of the "claimed Vendredi, actually posted Tuesday" bug: post
 * copy is generated by Claude with no ground-truth date in the prompt, and
 * the server's `new Date()` reflects the container's system timezone (not
 * necessarily Africa/Casablanca) — so any day-name text in generated copy is
 * either the model guessing/reusing an example, or computed against the
 * wrong clock. This module gives every content-generation path one place to
 * get the real Morocco date and to verify generated copy doesn't contradict
 * it before publish.
 */
import { recordFailure } from './alert.js';

const FRENCH_DAYS = ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'];
const TZ = 'Africa/Casablanca';

// Returns { dayName, dateStr, isoDate } anchored to Africa/Casablanca, computed fresh each call.
export function getCasablancaNow() {
  const now = new Date();
  const dayName = new Intl.DateTimeFormat('fr-FR', { timeZone: TZ, weekday: 'long' }).format(now);
  const dateStr = new Intl.DateTimeFormat('fr-FR', {
    timeZone: TZ, day: 'numeric', month: 'long', year: 'numeric',
  }).format(now);
  const isoDate = new Intl.DateTimeFormat('en-CA', { timeZone: TZ }).format(now); // YYYY-MM-DD
  return { dayName, dateStr, isoDate };
}

// Scans text for a French day-of-week name and checks it against the real
// current day in Casablanca. Returns { ok, foundDay, actualDay } — ok is
// true when no day name is mentioned, or the mentioned day matches reality.
export function checkDayClaim(text) {
  if (!text) return { ok: true, foundDay: null, actualDay: null };
  const { dayName: actualDay } = getCasablancaNow();
  const lower = text.toLowerCase();

  for (const day of FRENCH_DAYS) {
    const re = new RegExp(`\\b${day}\\b`, 'i');
    if (re.test(lower)) {
      return { ok: day === actualDay, foundDay: day, actualDay };
    }
  }
  return { ok: true, foundDay: null, actualDay };
}

/**
 * Validates generated post text before it's allowed to publish. On mismatch,
 * records a failure (Telegram alert + agent-failures.json) and returns
 * false so the caller can block publication / fall back to safe copy.
 *
 * @param {string} context label for the alert, e.g. "LinkedIn digest — post5Blog"
 * @param {string} text the generated post copy
 */
export async function validateDateClaim(context, text) {
  const { ok, foundDay, actualDay } = checkDayClaim(text);
  if (ok) return true;

  await recordFailure(
    `${context} — jour erroné dans le texte généré`,
    new Error(`Le texte mentionne "${foundDay}" mais nous sommes ${actualDay}. Publication bloquée.`)
  );
  return false;
}
